// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestion_etablissement;

namespace gestion_etablissement.Migrations
{
    [DbContext(typeof(GestionContext))]
    [Migration("20191210153446_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("gestion_etablissement.Models.Enseignant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("cout_horaires")
                        .HasColumnType("real");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("num_emp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Enseignant");
                });

            modelBuilder.Entity("gestion_etablissement.Models.Etudiant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Filiereid")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Filiereid");

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("gestion_etablissement.Models.Filiere", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("gestion_etablissement.Models.Matiere", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("intitule")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Matiere");
                });

            modelBuilder.Entity("gestion_etablissement.Models.Service", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codeid")
                        .HasColumnType("int");

                    b.Property<int?>("affectationid")
                        .HasColumnType("int");

                    b.Property<int>("coef")
                        .HasColumnType("int");

                    b.Property<string>("descriptif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("filid")
                        .HasColumnType("int");

                    b.Property<int?>("matid")
                        .HasColumnType("int");

                    b.Property<int>("nb_h")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("affectationid");

                    b.HasIndex("filid");

                    b.HasIndex("matid");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("gestion_etablissement.Models.Etudiant", b =>
                {
                    b.HasOne("gestion_etablissement.Models.Filiere", null)
                        .WithMany("Liste_etudiants")
                        .HasForeignKey("Filiereid");
                });

            modelBuilder.Entity("gestion_etablissement.Models.Service", b =>
                {
                    b.HasOne("gestion_etablissement.Models.Enseignant", "affectation")
                        .WithMany()
                        .HasForeignKey("affectationid");

                    b.HasOne("gestion_etablissement.Models.Filiere", "fil")
                        .WithMany("Liste_services")
                        .HasForeignKey("filid");

                    b.HasOne("gestion_etablissement.Models.Matiere", "mat")
                        .WithMany()
                        .HasForeignKey("matid");
                });
#pragma warning restore 612, 618
        }
    }
}
